services:
  - type: web
    name: fm-lite-26
    env: node
    region: oregon
    plan: free
    buildCommand: npm run install:all && cd client && npm run build
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
